import { BRAND_CTA, CONTENT_CATEGORIES, CONTENT_ROLES, EVIDENCE_STATES, HOOK_TYPES, MATERIAL_TYPES, NARRATIVE_TYPES } from "./ccps-rules.js";
import { buildArticle, platformRewrite, rotateDna } from "./ccps-content-engine.js";
import { runPreflight } from "./ccps-preflight.js";
import { readStore, writeStore } from "./ccps-storage.js";
const $=id=>document.getElementById(id); let current=null; let officialMaterials=[];
const fill=(id,items)=>$(id).innerHTML=items.map(x=>`<option>${x}</option>`).join("");
fill("category",CONTENT_CATEGORIES);fill("contentRole",CONTENT_ROLES);fill("hookType",HOOK_TYPES);fill("narrativeType",NARRATIVE_TYPES);fill("materialType",MATERIAL_TYPES);fill("materialEvidence",EVIDENCE_STATES);
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===b.dataset.tab));document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("primary",x===b));renderAll()});
const val=id=>$(id).value.trim();
function articleForm(){return {topic:val("topic"),category:val("category"),content_role:val("contentRole"),hook_type:val("hookType"),narrative_type:val("narrativeType"),visual_type:val("visualType"),CTA_type:BRAND_CTA,comment_question:val("commentQuestion"),goal:val("goal")}}
function showResult(article){current=article;if(article.blocked){$("gate").className="status fail";$("gate").textContent=article.code;$("output").textContent=article.code;renderChecks(article.checks||{});return}$("gate").className="status pass";$("gate").textContent=`PASS｜${article.dna_status}`;$("output").textContent=`文章角色：${article.role}\nHook：${article.hook}\n\nFB 正文：\n${article.body}\n\n留言問題：${article.comment_question}\n圖片建議：${article.image_suggestion}\nWhy Different：${article.why_different}`;renderChecks(article.checks)}
function renderChecks(c){$("checks").innerHTML=Object.entries(c||{}).map(([k,v])=>`<div class="status ${String(v).includes("FAIL")||String(v).includes("BLOCK")||String(v).includes("REQUIRED")?"fail":String(v).includes("WARN")?"warn":"pass"}"><b>${k}</b>：${Array.isArray(v)?(v.join("、")||"PASS"):v}</div>`).join("")}
$("generate").onclick=()=>showResult(buildArticle(articleForm(),readStore("posts",[])));
$("preflight").onclick=()=>renderChecks(runPreflight({...articleForm(),body:current?.body||""},readStore("posts",[])));
$("regenerate").onclick=()=>{const next=rotateDna(articleForm(),readStore("posts",[]));$("contentRole").value=next.content_role;$("hookType").value=next.hook_type;$("narrativeType").value=next.narrative_type;showResult(buildArticle(next,readStore("posts",[])))};
$("save").onclick=()=>{if(!current||current.blocked)return alert("只有通過 Evidence Gate 的文章可儲存。更多證據是下一步。");const posts=readStore("posts",[]);writeStore("posts",[{...current,id:crypto.randomUUID(),created_at:new Date().toISOString()},...posts].slice(0,100));renderAll()};
$("copy").onclick=()=>current&&!current.blocked&&navigator.clipboard.writeText(current.body);
$("download").onclick=()=>{if(!current||current.blocked)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([current.body],{type:"text/plain"}));a.download="CCPS_FB_Trust_Article.txt";a.click();URL.revokeObjectURL(a.href)};
$("rewrite").onclick=()=>$("platformOutput").textContent=current&&!current.blocked?Object.entries(platformRewrite(current)).map(([k,v])=>`【${k}】\n${v}`).join("\n\n"):"請先產生通過 Evidence Gate 的文章。";
$("saveMaterial").onclick=()=>{if(!val("materialTitle")||!val("materialBody"))return alert("請填素材標題與內容。");const items=readStore("materials",[]);items.unshift({id:crypto.randomUUID(),type:val("materialType"),title:val("materialTitle"),body:val("materialBody"),evidence_state:val("materialEvidence"),source:val("materialSource"),source_date:val("materialDate"),region:val("materialRegion"),property:val("materialProperty"),client_type:val("materialClient"),tags:val("materialTags"),freshness_required:$("materialFresh").checked,privacy_note:val("materialPrivacy")});writeStore("materials",items);renderMaterials()};
const fields=(prefix,ids)=>Object.fromEntries(ids.map(id=>[id.replace(prefix,""),val(id)]));
$("saveBrand").onclick=()=>writeStore("brand",fields("brand",["brandPosition","brandArea","brandAudience","brandTone","brandPrinciples","brandForbidden","brandEnding"]));
$("saveVoice").onclick=()=>writeStore("voice",fields("voice",["voiceTone","voiceColloquial","voicePerson","voiceWords","voiceForbidden","voiceNever","voicePrinciples","voiceExamples"]));
function hydrate(prefix,obj){Object.entries(obj||{}).forEach(([k,v])=>{const el=$(prefix+k);if(el)el.value=v})}
function renderMaterials(){const list=$("materialList");list.replaceChildren();const items=readStore("materials",[]);if(!items.length){list.textContent="尚無素材。";return}items.forEach(x=>{const row=document.createElement("article"),title=document.createElement("b"),meta=document.createElement("div"),body=document.createElement("div");title.textContent=`${x.type}｜${x.title}`;meta.textContent=`${x.evidence_state}｜${x.source_date||"無日期"}｜${x.region||"未指定區域"}`;body.className="muted";body.textContent=x.body;row.append(title,meta,body);list.append(row)})}
async function loadOfficialMaterials(){try{const [officialResponse,guideResponse,localResponse]=await Promise.all([fetch("./data/ccps-official-materials.json"),fetch("./data/ccps-malaysia-guide-materials.json"),fetch("./data/ccps-local-materials.json")]);if(!officialResponse.ok||!guideResponse.ok||!localResponse.ok)throw new Error(`${officialResponse.status}/${guideResponse.status}/${localResponse.status}`);const [officialData,guideData,localData]=await Promise.all([officialResponse.json(),guideResponse.json(),localResponse.json()]);officialMaterials=[...(officialData.materials||[]).map(x=>({...x,library_source:"CCPS 官網",visibility:"public_candidate"})),...(guideData.materials||[]).map(x=>({...x,library_source:"馬來西亞置產寶典",visibility:"public_candidate"})),...(localData.materials||[])];fill("officialSource",["",...new Set(officialMaterials.map(x=>x.library_source))]);fill("officialType",["",...new Set(officialMaterials.map(x=>x.type))]);$("officialSource").options[0].textContent="全部來源";$("officialSource").options[0].value="";$("officialType").options[0].textContent="全部分類";$("officialType").options[0].value="";renderOfficialMaterials()}catch{$("officialSummary").className="status fail";$("officialSummary").textContent="信任內容來源載入失敗，請稍後重新整理。"}}
function renderOfficialMaterials(){const q=val("officialSearch").toLowerCase(),source=val("officialSource"),type=val("officialType");const filtered=officialMaterials.filter(x=>(!source||x.library_source===source)&&(!type||x.type===type)&&(!q||`${x.title} ${x.body} ${x.region}`.toLowerCase().includes(q)));const officialCount=officialMaterials.filter(x=>x.library_source==="CCPS 官網").length,guideCount=officialMaterials.filter(x=>x.library_source==="馬來西亞置產寶典").length,localCount=officialMaterials.length-officialCount-guideCount;$("officialSummary").className="status pass";$("officialSummary").textContent=`共 ${officialMaterials.length} 筆｜官網 ${officialCount}｜置產寶典 ${guideCount}｜本機公開候選 ${localCount}｜目前顯示 ${Math.min(filtered.length,30)}／${filtered.length} 筆`;const list=$("officialList");list.replaceChildren();filtered.slice(0,30).forEach(item=>{const row=document.createElement("article"),title=document.createElement("b"),meta=document.createElement("div"),body=document.createElement("div"),actions=document.createElement("div"),button=document.createElement("button");title.textContent=`${item.type}｜${item.title}`;meta.textContent=`${item.library_source}｜${item.evidence_state}｜資料時點 ${item.source_date}｜${item.freshness_required?"需 Freshness":"一般"}`;body.className="muted";body.textContent=`${item.body.slice(0,260)}${item.body.length>260?"…":""}`;button.type="button";button.className="gold";button.textContent="加入我的素材庫";button.onclick=()=>importOfficialMaterial(item);actions.className="actions";actions.append(button);if(item.source.startsWith("https://")){const link=document.createElement("a");link.href=item.source;link.target="_blank";link.rel="noopener";link.textContent="查看來源";actions.append(link)}row.append(title,meta,body,actions);list.append(row)})}
function importOfficialMaterial(item){const items=readStore("materials",[]);if(items.some(x=>x.source===item.source))return alert("此來源已在你的素材庫中。");items.unshift({...item,id:crypto.randomUUID(),tags:Array.isArray(item.tags)?item.tags.join(","):item.tags});writeStore("materials",items.slice(0,200));renderMaterials();alert("已加入你的素材庫；生成前仍會套用 Evidence 與 Freshness Gate。")}
$("officialSearch").oninput=renderOfficialMaterials;$("officialSource").onchange=renderOfficialMaterials;$("officialType").onchange=renderOfficialMaterials;
function renderPosts(){const posts=readStore("posts",[]);$("postList").innerHTML=posts.map(x=>`<article><b>${x.content_role}｜${x.topic}</b><div>${x.hook_type}｜${x.narrative_type}</div><div class="muted">${x.body.slice(0,120)}…</div></article>`).join("")||"尚無文章。";$("trackingPost").innerHTML=posts.map(x=>`<option value="${x.id}">${x.topic}｜${x.content_role}</option>`).join("")}
$("buildCalendar").onclick=()=>{const days=Number(val("calendarDays")),posts=readStore("posts",[]);const start=new Date();$("calendarList").innerHTML=Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const role=CONTENT_ROLES[[0,0,1,1,3,2,4,4,5,6][i%10]];return `<article><b>${d.toLocaleDateString("zh-TW")}｜${role}</b><div>${CONTENT_CATEGORIES[i%CONTENT_CATEGORIES.length]}</div><div class="muted">${posts[i%Math.max(posts.length,1)]?.topic||"待建立證據素材"}｜CTA：${BRAND_CTA}</div></article>`}).join("")};
$("saveTracking").onclick=()=>{const id=val("trackingPost");if(!id)return alert("請先儲存一篇文章。");const post=readStore("posts",[]).find(x=>x.id===id);const number=id=>Number(val(id)||0),reach=number("reach");const item={post_id:id,content_role:post.content_role,hook_type:post.hook_type,narrative_type:post.narrative_type,visual_type:post.visual_type,CTA_type:post.CTA_type,reach,reactions:number("reactions"),comments:number("comments"),shares:number("shares"),saves:number("saves"),clicks:number("clicks"),inquiries:number("inquiries"),follows:number("follows"),qualitative_notes:val("qualitativeNotes")};item.scores={reach_score:reach,conversation_score:reach?(item.comments+item.inquiries)/reach:0,share_score:reach?item.shares/reach:0,utility_score:reach?(item.saves+item.clicks)/reach:0,trust_score:reach?(item.follows+item.inquiries)/reach:0,conversion_score:reach?item.inquiries/reach:0};const all=readStore("tracking",[]).filter(x=>x.post_id!==id);writeStore("tracking",[item,...all]);$("trackingResult").innerHTML=`<div class="status pass">已回填。Conversation ${(item.scores.conversation_score*100).toFixed(2)}%｜Share ${(item.scores.share_score*100).toFixed(2)}%｜Conversion ${(item.scores.conversion_score*100).toFixed(2)}%</div>`};
function renderAll(){renderMaterials();renderPosts();hydrate("brand",readStore("brand",{}));hydrate("voice",readStore("voice",{}))}renderAll();loadOfficialMaterials();
