import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";
const root=path.resolve(import.meta.dirname,"..");
const files=["index.html","ccps-rules.js","ccps-content-engine.js","ccps-storage.js","ccps-preflight.js","app.js","README.md","docs/CCPS_CONTENT_RULES.md"];
const text=files.filter(f=>fs.existsSync(path.join(root,f))).map(f=>fs.readFileSync(path.join(root,f),"utf8")).join("\n");
const rules=await import(pathToFileURL(path.join(root,"ccps-rules.js")));
const engine=await import(pathToFileURL(path.join(root,"ccps-content-engine.js")));
const preflight=await import(pathToFileURL(path.join(root,"ccps-preflight.js")));
const checks=[];const check=(name,pass,detail="")=>checks.push({name,pass:Boolean(pass),detail});
files.forEach(f=>check(`file:${f}`,fs.existsSync(path.join(root,f))));
check("7 roles",rules.CONTENT_ROLES.length===7);
check("hook types >= 9",rules.HOOK_TYPES.length>=9);
check("narratives >= 10",rules.NARRATIVE_TYPES.length>=10);
check("anti-cliche",rules.CLICHES.length>=12);
check("single similarity threshold source",Object.keys(rules.SIMILARITY_THRESHOLDS).length===2 && !/0\.25|0\.40/.test(fs.readFileSync(path.join(root,"ccps-preflight.js"),"utf8")));
check("storage namespace",Object.values(rules.STORAGE_KEYS).every(k=>k.startsWith("ccpsOs")));
check("no uncleHouse storage key",!text.includes("uncleHouse"));
check("no secret literal",!/(sk-[A-Za-z0-9_-]{8,}|EA[A-Za-z0-9]{30,})/.test(text));
check("evidence gate",text.includes("evidence_gate") && text.includes("EVIDENCE_REQUIRED"));
check("fabricated story gate",text.includes("fabricated_story_gate") && text.includes("FABRICATED_REAL_WORLD_EVENT"));
check("voice fingerprint",text.includes("CCPS 寫作指紋") && text.includes("Voice Fingerprint"));
check("tracking fields",rules.TRACKING_FIELDS.every(f=>text.includes(f)),rules.TRACKING_FIELDS.filter(f=>!text.includes(f)).join(","));
check("brand CTA",rules.BRAND_CTA==="追蹤ccps家慶佳業" && !/追蹤房叔|房叔自媒體學院/.test(text));
const base={topic:"MM2H 政策",content_role:"專業判斷",hook_type:"直接結論",narrative_type:rules.NARRATIVE_TYPES[1],evidence_state:"UNKNOWN",evidence:"",source_date:"",visual_type:"真實文件",CTA_type:rules.BRAND_CTA,comment_question:"你最想知道什麼？"};
check("unknown blocks generation",engine.buildArticle(base,[]).code==="EVIDENCE_REQUIRED");
const fake=preflight.runPreflight({...base,body:"昨天有位客戶問我們怎麼判斷"},[]);
check("fake story blocks",fake.fabricated_story_gate==="BLOCK: FABRICATED_REAL_WORLD_EVENT");
const good=engine.buildArticle({...base,evidence_state:"VERIFIED_CURRENT",evidence:"來源文件確認此案例的條件與日期。",source_date:"2026-08-25"},[]);
check("verified article output",!good.blocked && good.body.includes(rules.BRAND_CTA) && good.checks.brand_pov==="PASS");
const requiredUi=["生成文章","防 AI 檢查","重新生成不同 DNA","儲存文章","複製","下載","素材庫","內容月曆","成效回填"];
check("required UI",requiredUi.every(x=>text.includes(x)),requiredUi.filter(x=>!text.includes(x)).join(","));
checks.forEach(c=>console.log(`${c.pass?"PASS":"FAIL"} ${c.name}${c.detail?` — ${c.detail}`:""}`));
const failed=checks.filter(c=>!c.pass);console.log(`\n${checks.length-failed.length}/${checks.length} PASS`);process.exit(failed.length?1:0);

